

const countries = [
    { value: 'afghanistan', display: 'Afghanistan', timezone: 4.3 },
    { value: 'albania', display: 'Albania', timezone: 2 },
    { value: 'algeria', display: 'Algeria', timezone: 2 },
    { value: 'american_samoa', display: 'American Samoa', timezone: -11 },
    { value: 'angola', display: 'Angola', timezone: 1 },
    { value: 'anguilla', display: 'Anguilla', timezone: -4 },
    { value: 'argentina', display: 'Argentina', timezone: -3 },
    { value: 'armenia', display: 'Armenia', timezone: 4 },
    { value: 'aruba', display: 'Aruba', timezone: -4 },
    { value: 'australia', display: 'Australia', timezone: 10 },
    { value: 'austria', display: 'Austria', timezone: 1 },
    { value: 'azerbaijan', display: 'Azerbaijan', timezone: 4 },
    { value: 'bahamas', display: 'Bahamas', timezone: -5 },
    { value: 'bahrain', display: 'Bahrain', timezone: 3 },
    { value: 'bangladesh', display: 'Bangladesh', timezone: 6 },
    { value: 'barbados', display: 'Barbados', timezone: -4 },
    { value: 'belarus', display: 'Belarus', timezone: 3 },
    { value: 'belgium', display: 'Belgium', timezone: 1 },
    { value: 'belize', display: 'Belize', timezone: -6 },
    { value: 'benin', display: 'Benin', timezone: 1 },
    { value: 'bermuda', display: 'Bermuda', timezone: -4 },
    { value: 'bhutan', display: 'Bhutan', timezone: 6 },
    { value: 'bolivia', display: 'Bolivia', timezone: -4 },
    { value: 'botswana', display: 'Botswana', timezone: 2 },
    { value: 'brazil', display: 'Brazil', timezone: -5 },
    { value: 'brunei', display: 'Brunei', timezone: 8 },
    { value: 'bulgaria', display: 'Bulgaria', timezone: 2 },
    { value: 'burkina_faso', display: 'Burkina Faso', timezone: 0 },
    { value: 'burundi', display: 'Burundi', timezone: 2 },
    { value: 'cambodia', display: 'Cambodia', timezone: 7 },
    { value: 'cameroon', display: 'Cameroon', timezone: 1 },
    { value: 'canada', display: 'Canada', timezone: -6 },
    { value: 'cape_verde', display: 'Cape Verde', timezone: -1 },
    { value: 'cayman_islands', display: 'Cayman Islands', timezone: -5 },
    {
        value: 'central_african_republic',
        display: 'Central African Republic',
        timezone: 1
    },
    { value: 'chad', display: 'Chad', timezone: 1 },
    { value: 'chile', display: 'Chile', timezone: -3 },
    { value: 'china', display: 'China', timezone: 8 },
    {
        value: 'christmas_island',
        display: 'Christmas Island',
        timezone: 7
    },
    { value: 'colombia', display: 'Colombia', timezone: -5 },
    { value: 'comoros', display: 'Comoros', timezone: 3 },
    { value: 'cook_islands', display: 'Cook Islands', timezone: -10 },
    { value: 'costa_rica', display: 'Costa Rica', timezone: -6 },
    { value: 'croatia', display: 'Croatia', timezone: 1 },
    { value: 'cyprus', display: 'Cyprus', timezone: 2 },
    { value: 'czech_republic', display: 'Czech Republic', timezone: 1 },
    { value: 'denmark', display: 'Denmark', timezone: 1 },
    { value: 'djibouti', display: 'Djibouti', timezone: 3 },
    { value: 'dominica', display: 'Dominica', timezone: -4 },
    {
        value: 'dominican_republic',
        display: 'Dominican Republic',
        timezone: -4
    },
    { value: 'ecuador', display: 'Ecuador', timezone: -5 },
    { value: 'egypt', display: 'Egypt', timezone: 2 },
    { value: 'el_salvador', display: 'El Salvador', timezone: -6 },
    {
        value: 'equatorial_guinea',
        display: 'Equatorial Guinea',
        timezone: 1
    },
    { value: 'eritrea', display: 'Eritrea', timezone: 3 },
    { value: 'estonia', display: 'Estonia', timezone: 2 },
    { value: 'ethiopia', display: 'Ethiopia', timezone: 3 },
    { value: 'faroe_islands', display: 'Faroe Islands', timezone: 0 },
    { value: 'fiji', display: 'Fiji', timezone: 12 },
    { value: 'finland', display: 'Finland', timezone: 2 },
    { value: 'france', display: 'France', timezone: 1 },
    { value: 'french_guiana', display: 'French Guiana', timezone: -3 },
    {
        value: 'french_polynesia',
        display: 'French Polynesia',
        timezone: -10
    },
    { value: 'gabon', display: 'Gabon', timezone: 1 },
    { value: 'georgia', display: 'Georgia', timezone: 4 },
    { value: 'germany', display: 'Germany', timezone: 1 },
    { value: 'ghana', display: 'Ghana', timezone: 0 },
    { value: 'gibraltar', display: 'Gibraltar', timezone: 1 },
    { value: 'greece', display: 'Greece', timezone: 2 },
    { value: 'greenland', display: 'Greenland', timezone: -3 },
    { value: 'grenada', display: 'Grenada', timezone: -4 },
    { value: 'guadeloupe', display: 'Guadeloupe', timezone: -4 },
    { value: 'guam', display: 'Guam', timezone: 10 },
    { value: 'guatemala', display: 'Guatemala', timezone: -6 },
    { value: 'guinea', display: 'Guinea', timezone: 0 },
    { value: 'guyana', display: 'Guyana', timezone: -4 },
    { value: 'haiti', display: 'Haiti', timezone: -5 },
    { value: 'honduras', display: 'Honduras', timezone: -6 },
    { value: 'hong Kong', display: 'Hong Kong', timezone: 8 },
    { value: 'hungary', display: 'Hungary', timezone: 1 },
    { value: 'iceland', display: 'Iceland', timezone: 0 },
    { value: 'indonesia', display: 'Indonesia', timezone: 7 },
    { value: 'india', display: 'India', timezone: 5.3 },
    { value: 'iran', display: 'Iran', timezone: 3.3 },
    { value: 'iraq', display: 'Iraq', timezone: 3 },
    { value: 'ireland', display: 'Ireland', timezone: 0 },
    { value: 'israel', display: 'Israel', timezone: 2 },
    { value: 'italy', display: 'Italy', timezone: 1 },
    { value: 'jamaica', display: 'Jamaica', timezone: -5 },
    { value: 'japan', display: 'Japan', timezone: 9 },
    { value: 'jordan', display: 'Jordan', timezone: 2 },
    { value: 'kazakhstan', display: 'Kazakhstan', timezone: 5 },
    { value: 'kenya', display: 'Kenya', timezone: 3 },
    { value: 'kiribati', display: 'Kiribati', timezone: 12 },
    { value: 'kuwait', display: 'Kuwait', timezone: 3 },
    { value: 'kyrgyzstan', display: 'Kyrgyzstan', timezone: 6 },
    { value: 'laos', display: 'Laos', timezone: 7 },
    { value: 'latvia', display: 'Latvia', timezone: 2 },
    { value: 'lebanon', display: 'Lebanon', timezone: 2 },

    { value: 'lesotho', display: 'Lesotho', timezone: 2 },
    { value: 'liberia', display: 'Liberia', timezone: 0 },
    { value: 'libya', display: 'Libya', timezone: 1 },
    { value: 'liechtenstein', display: 'Liechtenstein', timezone: 1 },
    { value: 'lithuania', display: 'Lithuania', timezone: 2 },
    { value: 'luxembourg', display: 'Luxembourg', timezone: 1 },
    { value: 'macau', display: 'Macau', timezone: 8 },
    { value: 'madagascar', display: 'Madagascar', timezone: 3 },
    { value: 'malaysia', display: 'Malaysia', timezone: 8 },
    { value: 'malawi', display: 'Malawi', timezone: 2 },
    { value: 'maldives', display: 'Maldives', timezone: 5 },
    { value: 'mali', display: 'Mali', timezone: 0 },
    { value: 'malta', display: 'Malta', timezone: 0 },
    {
        value: 'marshall_islands',
        display: 'Marshall Islands',
        timezone: 12
    },
    { value: 'martinique', display: 'Martinique', timezone: -4 },
    { value: 'mauritania', display: 'Mauritania', timezone: 0 },
    { value: 'mauritius', display: 'Mauritius', timezone: 4 },
    { value: 'mayotte', display: 'Mayotte', timezone: 3 },
    { value: 'mexico', display: 'Mexico', timezone: -6 },
    { value: 'midway_islands', display: 'Midway Islands', timezone: -11 },
    { value: 'moldova', display: 'Moldova', timezone: 2 },
    { value: 'monaco', display: 'Monaco', timezone: 1 },
    { value: 'mongolia', display: 'Mongolia', timezone: 8 },
    { value: 'montserrat', display: 'Montserrat', timezone: -4 },
    { value: 'morocco', display: 'Morocco', timezone: 0 },
    { value: 'mozambique', display: 'Mozambique', timezone: 2 },
    { value: 'nauru', display: 'Nauru', timezone: 12 },
    { value: 'nepal', display: 'Nepal', timezone: 5.45 },
    { value: 'new_zealand', display: 'New Zealand', timezone: 12 },
    { value: 'nicaragua', display: 'Nicaragua', timezone: -6 },
    { value: 'niger', display: 'Niger', timezone: 1 },
    { value: 'nigeria', display: 'Nigeria', timezone: 1 },
    { value: 'niue', display: 'Niue', timezone: -11 },
    {
        value: 'norfolk_island',
        display: 'Norfolk Island',
        timezone: 11.3
    },
    { value: 'norway', display: 'Norway', timezone: 1 },
    { value: 'oman', display: 'Oman', timezone: 4 },
    { value: 'pakistan', display: 'Pakistan', timezone: 5 , countryCode: +92 },
    { value: 'panama', display: 'Panama', timezone: -5 },
    {
        value: 'papua_new_guinea',
        display: 'Papua New Guinea',
        timezone: 10
    },
    { value: 'paraguay', display: 'Paraguay', timezone: -4 },
    { value: 'peru', display: 'Peru', timezone: -5 },
    { value: 'phillipines', display: 'Philippines', timezone: 8 },
    { value: 'poland', display: 'Poland', timezone: 1 },
    { value: 'portugal', display: 'Portugal', timezone: 0 },
    { value: 'puerto_rico', display: 'Puerto Rico', timezone: -4 },
    { value: 'qatar', display: 'Qatar', timezone: 3 },
    { value: 'reunion_islands', display: 'Reunion Islands', timezone: 4 },
    { value: 'russia', display: 'Russia', timezone: 0 },
    { value: 'rwanda', display: 'Rwanda', timezone: 2 },
    { value: 'samoa', display: 'Samoa', timezone: 13 },
    { value: 'san_marino', display: 'San Marino', timezone: 1 },
    { value: 'saudi_arabia', display: 'Saudi Arabia', timezone: 3 },
    { value: 'senegal', display: 'Senegal', timezone: 0 },
    { value: 'seychelles', display: 'Seychelles', timezone: 4 },
    { value: 'sierra_leone', display: 'Sierra Leone', timezone: 0 },
    { value: 'singapore', display: 'Singapore', timezone: 8 },
    { value: 'slovakia', display: 'Slovakia', timezone: 1 },
    { value: 'slovenia', display: 'Slovenia', timezone: 1 },
    {
        value: 'solomon_islands',
        display: 'Solomon Islands',
        timezone: 11
    },
    { value: 'somalia', display: 'Somalia', timezone: 3 },
    { value: 'south_africa', display: 'South Africa', timezone: 2 },
    { value: 'spain', display: 'Spain', timezone: 1 },
    { value: 'sri_lanka', display: 'Sri Lanka', timezone: 5.3 },
    { value: 'sudan', display: 'Sudan', timezone: 3 },
    { value: 'suriname', display: 'Suriname', timezone: -3 },
    { value: 'swaziland', display: 'Swaziland', timezone: 2 },
    { value: 'sweden', display: 'Sweden', timezone: 1 },
    { value: 'switzerland', display: 'Switzerland', timezone: 1 },    
    { value: 'syria', display: 'Syria', timezone: 2 },
    { value: 'taiwan', display: 'Taiwan', timezone: 8 },
    { value: 'tajikistan', display: 'Tajikistan', timezone: 5 },
    { value: 'tanzania', display: 'Tanzania', timezone: 3 },
    { value: 'thailand', display: 'Thailand', timezone: 7 },
    { value: 'togo', display: 'Togo', timezone: 0 },
    { value: 'tokelau', display: 'Tokelau', timezone: 13 },
    { value: 'tonga', display: 'Tonga', timezone: 13 },
    { value: 'tunisia', display: 'Tunisia', timezone: 1 },
    { value: 'turkey', display: 'Turkey', timezone: 2 },
    { value: 'turkmenistan', display: 'Turkmenistan', timezone: 5 },
    { value: 'tuvalu', display: 'Tuvalu', timezone: 12 },
    { value: 'uganda', display: 'Uganda', timezone: 3 },
    { value: 'united_kingdom', display: 'United Kingdom', timezone: 0 },
    { value: 'ukraine', display: 'Ukraine', timezone: 2 },
    {
        value: 'united_arab_erimates',
        display: 'United Arab Emirates',
        timezone: 4
    },
    { value: 'uraguay', display: 'Uruguay', timezone: -3 },
    { value: 'uzbekistan', display: 'Uzbekistan', timezone: 5 },
    { value: 'vanuatu', display: 'Vanuatu', timezone: 11 },
    { value: 'venezuela', display: 'Venezuela', timezone: -4.3 },
    { value: 'vietnam', display: 'Vietnam', timezone: 7 },
    { value: 'yemen', display: 'Yemen', timezone: 3 },
    { value: 'zambia', display: 'Zambia', timezone: 1 },
    { value: 'zimbabwe', display: 'Zimbabwe', timezone: 2 }
]

export default countries
